# Generated by Django 4.2.7 on 2026-04-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.TextField()),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('device_name', models.CharField(max_length=100)),
                ('risk_level', models.CharField(default='low', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_trusted', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('threat_type', models.CharField(choices=[('ddos', 'DDoS'), ('sqli', 'SQL Injection'), ('brute_force', 'Brute Force'), ('phishing', 'Phishing'), ('ransomware', 'Ransomware'), ('mitm', 'MITM'), ('zero_day', 'Zero-Day'), ('apt', 'APT'), ('port_scan', 'Port Scan'), ('anomaly', 'Anomaliya')], max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Kritik'), ('high', 'Yuqori'), ('medium', "O'rta"), ('low', 'Past')], max_length=20)),
                ('probability', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_local', models.BooleanField(default=False)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('algorithm', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
