# Generated by Django 4.2.7 on 2026-04-20 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_type', models.CharField(choices=[('ssh', 'SSH'), ('snmp', 'SNMP')], max_length=20)),
                ('target_host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=22)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('secret_encrypted', models.TextField(blank=True)),
                ('snmp_version', models.CharField(choices=[('2c', 'SNMP v2c'), ('3', 'SNMP v3')], default='2c', max_length=10)),
                ('network_label', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'target_host'],
            },
        ),
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('network_name', models.CharField(blank=True, max_length=120)),
                ('interface_name', models.CharField(blank=True, max_length=120)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='threats.connectionprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
