# Generated by Django 4.2.7 on 2026-04-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0004_alter_connectionprofile_profile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('requested_ports', models.JSONField(blank=True, default=list)),
                ('open_ports', models.JSONField(blank=True, default=list)),
                ('timeout_seconds', models.FloatField(default=0.35)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('threat_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('attack_type', models.CharField(choices=[('normal', 'Normal'), ('ddos', 'DDoS'), ('brute_force', 'Brute Force'), ('anomaly', 'Anomaly')], default='normal', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('intel', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrafficEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField()),
                ('traffic_type', models.CharField(choices=[('normal', 'Normal'), ('ddos', 'DDoS Simulation'), ('brute_force', 'Brute Force Simulation')], max_length=20)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('packet_size_avg', models.FloatField(default=0.0)),
                ('connection_frequency', models.FloatField(default=0.0)),
                ('source', models.CharField(default='simulator', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
