# Generated by Django 4.2.7 on 2026-04-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0005_ipanalysisrecord_trafficeventlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('format_type', models.CharField(choices=[('nsl_kdd', 'NSL-KDD'), ('cicids2017', 'CICIDS2017'), ('unsw_nb15', 'UNSW-NB15'), ('custom', 'Custom CSV')], default='custom', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('feature_count', models.PositiveIntegerField(default=0)),
                ('classes', models.JSONField(default=list)),
                ('is_trained', models.BooleanField(default=False)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rule_name', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Kritik'), ('high', 'Yuqori'), ('medium', "O'rta"), ('low', 'Past')], default='medium', max_length=20)),
                ('threat_type', models.CharField(default='anomaly', max_length=50)),
                ('involved_ips', models.JSONField(default=list)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
