# Generated by Django 4.2.7 on 2026-05-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('failed_logins', models.IntegerField(default=0)),
                ('success_logins', models.IntegerField(default=0)),
                ('new_processes', models.IntegerField(default=0)),
                ('policy_changes', models.IntegerField(default=0)),
                ('service_events', models.IntegerField(default=0)),
                ('label', models.CharField(choices=[('normal', 'Normal'), ('brute_force', 'Brute Force'), ('port_scan', 'Port Scan'), ('anomaly', 'Anomaly')], default='normal', max_length=20)),
                ('source', models.CharField(default='collector', max_length=20)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrainSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('f1', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('roc_auc', models.FloatField(blank=True, null=True)),
                ('train_rows', models.IntegerField(default=0)),
                ('model_path', models.CharField(blank=True, max_length=255)),
                ('error_msg', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
