# Generated by Django 4.2.7 on 2026-05-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logwindow',
            name='running_processes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logwindow',
            name='tcp_connections',
            field=models.IntegerField(default=0),
        ),
    ]
