# Generated by Django 4.2.7 on 2026-05-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_logwindow_running_processes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainsession',
            name='classes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainsession',
            name='confusion_matrix',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
