# Generated by Django 4.2.7 on 2026-05-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_trainsession_classes_trainsession_confusion_matrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('prediction', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('prob_normal', models.FloatField(default=0)),
                ('prob_brute_force', models.FloatField(default=0)),
                ('prob_port_scan', models.FloatField(default=0)),
                ('prob_anomaly', models.FloatField(default=0)),
                ('triggered_by', models.CharField(default='auto', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='trainsession',
            name='per_class',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
